### ISSUE TITLE
Thresholds outside of minValue/maxValue are removed.

### ISSUE THREAD

**Issue by kapace** [janstol/signal_strength_indicator#1]
According to the documentation, you can specify levels like this:
```dart
SignalStrengthIndicator.bars(
  value: val,
  minValue: 0,
  maxValue: 100,
  levels: <num, Color>{
    0.25: Colors.red,
    0.50: Colors.yellow,
    0.75: Colors.green,
  },
)
```

However, if the minValue and maxValue do not contain the levels as specified in levels, they will be removed. This doesn't make sense, since the min/max could be an entirely different range than the levels. For example, this will not use any of the specified levels because they will be removed:

```dart
SignalStrengthIndicator.bars(
  value: client["signal"],
  spacing: 0.3,
  minValue: -88,
  maxValue: -30,
  levels: <num, Color>{
    0.12: Colors.red,   // These levels will all be removed, because they fall outside of the min/max range!
    0.21: Colors.yellow,
    0.39: Colors.green, 
    0.65: Colors.green, 
    0.87: Colors.green,
  }, 
),
```

I believe the one line fix is to just remove: https://github.com/janstol/signal_strength_indicator/blob/446b6a68b34343ed6768a9977c17deb49714d43e/lib/src/style/bar_signal_strength_indicator_style.dart#L60

**Comment by janstol** [comment]
Hi, I couldn't find where I use the code you mentioned. In the example, I use
```dart
SignalStrengthIndicator.bars(
  value: _signalStrength,
  barCount: 3,
  levels: <num, Color>{
    0.25: Colors.red,
    0.50: Colors.yellow,
    0.75: Colors.green,
  },
)
```
which sets `minValue` to 0.0 and `maxValue` to 1.0 by default.
https://github.com/janstol/signal_strength_indicator/blob/446b6a68b34343ed6768a9977c17deb49714d43e/lib/src/style/signal_strength_indicator_style.dart#L25-L26

And `levels` values are absolute, not relative (like percentage).

For `minValue` 0 and `maxValue` 100 it should look like this.
```dart
SignalStrengthIndicator.bars(
  value: val,
  minValue: 0,
  maxValue: 100,
  levels: <num, Color>{
    25: Colors.red,
    50: Colors.yellow,
    75: Colors.green,
  },
)
```

And in you case (hope I calculated those values correctly):
```dart
SignalStrengthIndicator.bars(
  value: client["signal"],
  spacing: 0.3,
  minValue: -88,
  maxValue: -30,
  levels: <num, Color>{
    -81.4: Colors.red,
    -75.82: Colors.yellow,
    -65.38: Colors.green, 
    -50.3: Colors.green, 
    -47.54: Colors.green,
  }, 
),
```

Sorry if this is confusing, I should probably create proper documentation.

**Comment by kapace** [comment]
Thanks for your reply Jan!

Hmm, from what I can see using the latest version of the package, it does not work as you describe (although, it would be ideal if it did work like this!)

The documentation I refer to is here: https://pub.dev/documentation/signal_strength_indicator/latest/signal_strength_indicator/SignalStrengthIndicator/SignalStrengthIndicator.bars.html

https://github.com/janstol/signal_strength_indicator/blob/446b6a68b34343ed6768a9977c17deb49714d43e/lib/src/style/bar_signal_strength_indicator_style.dart#L55 
Here the value is being normalized to the 0.0-1.0 range, and this value is used to match against the "levels" thresholds. 

I tried to use your suggested parameters but it does not work as expected.

**Comment by janstol** [comment]
Oh, sorry, you are right. Looks like I mixed it up there...

So I made an update and it should work now.

```dart
SignalStrengthIndicator.bars(
  value: client["signal"],
  barCount: 5,
  spacing: 0.3,
  minValue: -88,
  maxValue: -30,
  levels: <num, Color>{
    -81.4: Colors.red,
    -75.82: Colors.yellow,
    -65.38: Colors.green, 
    -50.3: Colors.green, 
    -47.54: Colors.green,
  }, 
)
```

**Comment by kapace** [comment]
I saw the commit, amazing work! I had a one line fix that was not as robust.
Thank you for building this package and fixing this issue. 👍
